In [1]:
import numpy as np

In [2]:
# 3.1

In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

In [4]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [5]:
print(np.mean(arr))

24.4


In [6]:
print(np.median(arr))

23.5


In [7]:
print(np.std(arr))

13.828955130450023


In [8]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [9]:
print(arr[6])
print(arr[7])

4
50


In [10]:
print(np.min(arr))
print(np.max(arr))
# They match above!

4
50


In [11]:
greater_than_twenty = arr > 20
new_array = arr[greater_than_twenty]
print(new_array)

[27 31 50 39 35]


In [12]:
# 3.2

In [13]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
arr = np.array(matrix)

In [14]:
arr.shape

(3, 4)

In [15]:
print(arr[:,2])

[17 14 19]


In [16]:
print(arr[1,:])

[ 8 21 14  3]


In [17]:
print(arr*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [18]:
print(np.mean(arr, axis=0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [19]:
print(np.mean(arr))

11.5


In [20]:
np.max(arr, axis=1)

array([17, 21, 19])

In [21]:
np.min(arr, axis=0)

array([ 5, 12, 14,  3])

In [22]:
arr.flatten()
# the array now only has one row, it is squished into a list

array([ 5, 12, 17,  9,  8, 21, 14,  3,  6, 13, 19, 11])

In [23]:
print(np.argmin(arr))
print(np.argmax(arr))

7
5


In [24]:
arr2 = arr.flatten()
np.unravel_index((5,7), (3,4))

(array([1, 1]), array([1, 3]))

In [25]:
big_boy_matrix = arr > 15
arr[big_boy_matrix]

array([17, 21, 19])

In [26]:
np.sort(arr)

array([[ 5,  9, 12, 17],
       [ 3,  8, 14, 21],
       [ 6, 11, 13, 19]])

In [27]:
# 4 Prime Star Systems

In [28]:
magnitudes = np.array([    
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])
i = 2
for row in magnitudes:
    for number in row:
        is_prime = True
        for i in range(2, int(number ** 0.5) + 1):
              if number % i == 0:
                  is_prime = False
    if is_prime:
        print(row)

[2 3 5]
[11 13 17]
[ 7 10 13]


In [29]:
# 5 Let's Play Checkers

In [30]:
# 5.1

In [31]:
board = np.zeros((8,8))
print(board)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
# 5.2

In [33]:
board = np.zeros((8,8))
for i in range(board.shape[0]):
    if i % 2 != 0:       
        for j in range(board.shape[1]):
            if (i+j) % 2 == 0:
                board[i,j] = 1
print(board)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [34]:
# 5.3

In [35]:
board = np.zeros((8,8))
for i in range(board.shape[0]):
    for j in range(board.shape[1]):
        if (i+j) % 2 == 0:
            board[i,j] = 1
print(board)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [36]:
# 5.4

In [37]:
for row in board:
    print(row[::-1])

[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]


In [38]:
# 6 The Expanding Unverse

In [57]:
universe = np.array(['galaxy', 'clusters'])

def expansion(array, a):
    spaces = a * ' '
    for word in array:
        expanded_word = spaces.join(word)
        print(expanded_word)
expansion(universe, 4)

g    a    l    a    x    y
c    l    u    s    t    e    r    s


In [40]:
a = 2 * 'a'
print(a)

aa


In [41]:
# 7 Second_Brightest Star

In [42]:
np.random.seed(123)
stars = np.random.randint(500,2000, (5,5))
print(stars)
for row in np.sort(stars):
    print(row[-2:-1])

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889]
[1647]
[1138]
[1863]
[1592]
